### PR TITLE
Instructions for running locally

### PR DESCRIPTION
**Pull request by nottrobin**
Instructions for getting this running locally, that kinda worked for me. Better than nothing.

### CODE REVIEW

**Comment by jpmartinspt** [comment]
Thanks for writing this down, did you get to try dotrun v2 on this? I think this predates the snap version and I used to run it with `./run`?

**Comment by nottrobin** [comment]
Yeah I tried dotrun v2. Giving docker access to kubectl is tricky, I didn't solve that.

Don't think I tried ./run, maybe that's the easier way

**Comment by nottrobin** [comment]
@jpmartinspt `./run` gave me this error:

``` bash
error postcss-cli@9.1.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.15.3"
error Found incompatible module
```

But also, thinking about it, why would it work any better than dotrun v2? Both use Docker. Have you specifically changed the `./run` script to share the `~/.kube` directory with it or something? If not, I don't think this is going to be trivial. Could we just merge this as better than the previous complete lack of a README?

**Review by jpmartinspt — APPROVED** [review]
Yeah, for sure, I was just wondering, please merge away.

**Pull request merged**
